"""baseline

Revision ID: 6903f4f425f4
Revises:
Create Date: 2026-09-26 17:46:44.373672

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6903f4f425f4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
